const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

$('#enterBtn')?.addEventListener('click',()=>$('#workspace')?.scrollIntoView({behavior:reduce?'auto':'smooth'}));
window.addEventListener('scroll',()=>$('.topbar')?.classList.toggle('scrolled',window.scrollY>24),{passive:true});
$$('.cap-card').forEach(card=>card.addEventListener('mouseenter',()=>{$$('.cap-card').forEach(c=>c.classList.remove('active'));card.classList.add('active')}));

const modal=$('#mediaModal'),modalContent=$('#modalContent');
function openModal(html){if(!modal||!modalContent)return;modalContent.innerHTML=html;modal.showModal()}
$('.modal-close')?.addEventListener('click',()=>modal?.close());
modal?.addEventListener('click',e=>{if(e.target===modal)modal.close()});
$$('[data-img]').forEach(el=>el.addEventListener('click',()=>openModal(`<img src="${el.dataset.img}" alt="${el.dataset.title||'Portfolio work'}"><div class="modal-caption">${el.dataset.title||''}</div>`)));
$$('.video-tile').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.drive;openModal(`<iframe src="https://drive.google.com/file/d/${id}/preview" allow="autoplay" style="height:min(76vh,760px)"></iframe>`)}));
$('[data-modal="fmr"]')?.addEventListener('click',()=>openModal(`<div class="micro-label">FMR-5S · INTEGRATED CAMPAIGN</div><h2 style="font:700 clamp(42px,7vw,90px)/.95 Manrope;margin:16px 0 30px;letter-spacing:-.05em">Campaign system,<br>not a single post.</h2><div class="case-links"><a href="https://www.linkedin.com/feed/update/urn:li:activity:7478409013731401729" target="_blank" rel="noreferrer"><span>Teaser / Engagement · Quiz</span><b>↗</b></a><a href="https://www.linkedin.com/feed/update/urn:li:activity:7482383387341807616" target="_blank" rel="noreferrer"><span>Teaser · Video</span><b>↗</b></a><a href="https://www.linkedin.com/feed/update/urn:li:activity:7483822983317307392" target="_blank" rel="noreferrer"><span>Launch · Key Visual</span><b>↗</b></a><a href="https://www.linkedin.com/feed/update/urn:li:activity:7485992349450305536" target="_blank" rel="noreferrer"><span>Product Education · Brochure</span><b>↗</b></a><a href="https://www.linkedin.com/feed/update/urn:li:activity:7493586161316126720" target="_blank" rel="noreferrer"><span>Creative Extension · Video</span><b>↗</b></a><a href="https://www.linkedin.com/feed/update/urn:li:activity:7500100034567254016" target="_blank" rel="noreferrer"><span>Launch · Hero Video</span><b>↗</b></a></div>`));

if(window.gsap&&!reduce){gsap.registerPlugin(ScrollTrigger);gsap.from('.entry-copy>*',{opacity:0,y:28,duration:.8,stagger:.08,ease:'power3.out'});gsap.to('.entry-orbit',{rotation:22,duration:18,repeat:-1,yoyo:true,ease:'sine.inOut'});$$('.workspace-intro,.cap-card,.campaign-copy,.work-strip,.archive-stage,.directed-stage,.build-transition,.about>*').forEach(el=>gsap.from(el,{opacity:0,y:36,duration:.8,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 86%',once:true}}));gsap.to('.m1',{y:-28,scrollTrigger:{trigger:'.campaign-stage',start:'top bottom',end:'bottom top',scrub:1.2}});gsap.to('.m2',{y:34,scrollTrigger:{trigger:'.campaign-stage',start:'top bottom',end:'bottom top',scrub:1.1}});gsap.to('.m3',{y:-18,scrollTrigger:{trigger:'.campaign-stage',start:'top bottom',end:'bottom top',scrub:1.4}})}

if(window.THREE&&!reduce){const canvas=$('#three-canvas');if(canvas){const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);camera.position.z=6;const geo=new THREE.IcosahedronGeometry(1.45,1),mat=new THREE.MeshBasicMaterial({color:0xff5d2a,wireframe:true,transparent:true,opacity:.09}),mesh=new THREE.Mesh(geo,mat);mesh.position.set(2.6,.4,0);scene.add(mesh);canvas.style.cssText='position:fixed;inset:0;width:100%;height:100%;pointer-events:none;z-index:0';function tick(){mesh.rotation.x+=.0012;mesh.rotation.y+=.0018;renderer.render(scene,camera);requestAnimationFrame(tick)}tick();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}}